Add use warnings;
Recomendation from CPANTS:

http://cpants.cpanauthors.org/dist/POE-Loop-EV

```
use_warnings
Add 'use warnings' (or its equivalents) to all modules (this will require
perl > 5.6), or convince us that your favorite module is well-known enough
and people can easily see the modules warn when something bad happens.

Error: POE::Loop::EV
```

This PR belong to my montly PR-Challenge